# Generated by Django 4.0.5 on 2022-08-16 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0006_remove_instalaciones_texto_remove_nosotros_texto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instalaciones',
            name='body',
        ),
        migrations.RemoveField(
            model_name='instalaciones',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='nosotros',
            name='body',
        ),
        migrations.AddField(
            model_name='instalaciones',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='instalaciones'),
        ),
        migrations.AddField(
            model_name='nosotros',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='nosotros'),
        ),
        migrations.AlterField(
            model_name='avatar',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='agragarAvatar'),
        ),
    ]
